---
language: c
branches:
  only:
    - master
    - ci

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake make gcc bison build-essential texlive-latex-{recommended,extra} texlive-fonts-{recommended,extra} poppler-utils latex2html texlive-humanities texlive
  - sudo wget http://spinroot.com/spin/Src/src645.tar.gz -O /tmp/spin.tar.gz
  - sudo tar xf /tmp/spin.tar.gz
  - sudo make -C Src6.4.5
  - sudo make -C Src6.4.5 install
  - sudo wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz -O /tmp/cmake.tar.gz
  - sudo tar xf /tmp/cmake.tar.gz
  - cd cmake-3.5.2 && sudo cmake . && sudo make && sudo make install && cd ..

script:
  - cd src && mkdir build && cd build && cmake .. && make && cd .. && cd ..
  - cd doc/report && mkdir build && cd build && cmake .. && make && cd .. && cd .. && cd ..
  - cd doc/presentation && mkdir build && cd build && cmake .. && make && cd .. && cd .. && cd ..
