---
language: c
branches:
  only:
    - master
    - ci
sudo: required
services:
  - docker

before_install:
  - git submodule update --init --recursive

install:
  - docker pull hamroctopus/spin
  - docker pull hamroctopus/latex-cmake

script:
  - mkdir -p src/build doc/report/build doc/presentation/build
  - docker run -t -v $(pwd):/data hamroctopus/spin /bin/bash -c "cd /data/src/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake /bin/bash -c "cd /data/doc/report/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake /bin/bash -c "cd /data/doc/presentation/build && cmake .. && make"

after_success:
  - mkdir $HOME/deliverables && cp -fv doc/report/build/report.pdf doc/presentation/build/presentation.pdf $HOME/deliverables
  - bin/hook-travis-publish-docs.sh

dd:
  secure: nQlQbMhzep2ew+c5deZwrCX7ZdrEtkjm6g+zs5WC9kYZcLEsscyORBVaQxSqB2+JynFe+anpQqukRfF3CSWWWDtKCDMZBHUbLP6mExp8SP8GJ9uQrmHHZy7lMrMwzq7+wN5Wi3ICquMkP19FkLCRXzQYFrQlncGUH1nvLMFMrUrl2JvS8Egq4nGnl3F3e4UwQYSdJiIkPMOwXAY2U28BfVFBjHCbNBHLMkaG+UbYN+2gmnpfyn+kCvA6mUGqz32qhvINjMCZaKc0K/UkcPHOxJm62pFSeJWXyRt0vD6Jg7IskwjGgwcdBErZrGQaYVsDo2dv2d3wOXCos3oCxqC3PnNUEJhmVlDOo3/A3nv6PgofrNkf/uG8fKzYjIDLeye2PQojp10rGQBXuybKM1QsW26xs/dLP3pAjRy7gecGcc1RFG8Js3NEo9bMD19B0R7+BQ72yDW+sswapLWGsGIYl50PfL7aK1Lxgjt3XQy1f1VrP17rbbwUQmDy13JGF3x7dorV1tlvfM8014DdbZpAfBYsPOQMiW5Xm/UdCM/7Unq0qUX7/bYhf2rCunKpfjTEhX0f9k9AnuO9soydx90IK7c4o3hurKZW2CmMr2iaETQuXj/jr9JGi6PZLtK9OLUSTXszHpmxublkZ7YESoO2yQSmJuLzyaRFKxSEPjoAzTA=
