---
language: c
branches:
  only:
    - master
    - ci

sudo: required
services:
  - docker

before_install:
  - git submodule update --init --recursive

install:
  - docker pull hamroctopus/spin
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake make gcc bison build-essential texlive-latex-{recommended,extra} texlive-fonts-{recommended,extra} poppler-utils latex2html texlive-humanities texlive

script:
  - cd src && mkdir build && cd build && cd ../..
  - docker run -it -v $(pwd):/data hamroctopus/spin /bin/bash -c "cd /data/src/build && cmake .. && make"
  - cd doc/report && mkdir build && cd build && cmake .. && make && cd .. && cd .. && cd ..
  - echo "cd doc/presentation && mkdir build && cd build && cmake .. && make && cd .. && cd .. && cd .."
