---
language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake make gcc bison build-essential
  - sudo wget http://spinroot.com/spin/Src/src645.tar.gz -O /tmp/spin.tar.gz
  - sudo tar xf /tmp/spin.tar.gz
  - sudo make -C Src6.4.5
  - sudo make -C Src6.4.5 install
  - sudo wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - sudo tar xf /tmp/cmake.tar.gz
  - cd cmake-3.5.2-Linux-x86_64 && cmake . && cd ..
  - sudo make -C cmake-3.5.2-Linux-x86_64
  - sudo make -C cmake-3.5.2-Linux-x86_64 install

script:
  - cd src && mkdir build && cd build && cmake .. && make
