---
language: c
branches:
  only:
    - master
    - ci
sudo: required
services:
  - docker

before_install:
  - git submodule update --init --recursive

install:
  - docker pull hamroctopus/spin:6.4.5
  - docker pull hamroctopus/latex-cmake:3.4.0

script:
  - mkdir -p src/build doc/report/build doc/presentation/build
  - docker run -t -v $(pwd):/data hamroctopus/spin:6.4.5 "cd /data/src/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake:3.4.0 "cd doc/report/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake:3.4.0 "cd doc/presentation/build && cmake .. && make"

after_success:
  - mkdir $HOME/deliverables && cp -fv doc/report/build/report.pdf doc/presentation/build/presentation.pdf $HOME/deliverables
  - bin/hook-travis-publish-docs.sh

env:
  global:
    - GH_REF: github.com/stormosson/camelot.git
    - secure: T9mvWDB1CCCB+BfGqGvjrFOsIJhgO4Iy9Dy9SngTlZWkVbc6s7SOCYnmbeoYEPpKR/EXuA13tPSYzo98fGzdD47wQj+x/Ftx0lcRHfbA5V9XBuhco5M4VvYoLTbL5Y4IaHgEIMDNU5ueUvMdZmtuu1Ep5tlMljOvp88Mr731U+RstxwBEsx+U7b27z5Rz+VLE89i26Zez/eS0PpxI1SNhiCBf3DsZ/n2Ceczzj+0rDa851QvOllZyxVrL8b7tqtmV2Bteqf0mukZRWU1JrN3ny6QWxoHmcyv+v06SiIKmkBdoASzY7yuPs6scX+co+e3HmGFa9HJhA6iWRZhacNOxSFnh4LooDE/eBLToR4/B3WrRA378BKeNVb93G0EsT8C2WG0aiVg3zVVLnqTD8aGbfmWJJjHol+YGqcI88xZbDgFwxK07rvQk7862fhmOvFJCny7yB/IsHZwrJYNdu8seySVSHGE4WV0WbD6skcTc/b9eRJPoyR5ZSbgHBv2Tqt8FWe7sDT/848g3xX0BWCVDWNtzb3h5z4hreeyGNYY4BijhXIIDLdU8sYg8X9whrJ7brce1ZG3EJv73rY84gRv2RQMyy1ILdyzAA4hHz1s5ZuYSkW0OcccsWMAqLLj5/LVXRY3ZsVxxY3acV2HHsxy6MsH7j81XWoaZOxM6yyZnrY=
