---
language: c
branches:
  only:
    - master
    - ci
sudo: required
services:
  - docker

before_install:
  - git submodule update --init --recursive

install:
  - docker pull hamroctopus/spin
  - docker pull hamroctopus/latex-cmake

script:
  - mkdir -p src/build doc/report/build doc/presentation/build
  - docker run -t -v $(pwd):/data hamroctopus/spin /bin/bash -c "cd /data/src/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake /bin/bash -c "cd /data/doc/report/build && cmake .. && make"
  - docker run -t -v $(pwd):/data hamroctopus/latex-cmake /bin/bash -c "cd /data/doc/presentation/build && cmake .. && make"

after_success:
  - mkdir $HOME/deliverables && cp -fv doc/report/build/report.pdf doc/presentation/build/presentation.pdf $HOME/deliverables
  - bin/hook-travis-publish-docs.sh

env:
  global:
    secure: "oHsmA1GLIYhVYgR87MoHgLf81aUrzrPAPJCGUQ+Hlx9R2bT33q7geakUaPfLM2MFoyVKmAbU8ngzT+UgfLV66g5DrL2UMcqakPhs9ChRkXe7L312Y8tJE9bmxWiuHBoZv36yWNjfag7chf4YvqlF61wHoHEFyyT+xbN/+vu/RKyCnH0JdJj9bxutpVTHeOlgRJ2Mh5qujAx0Fvb0bwvApM/lgy5q+dZam3lumCY34dMBOCSKdWP1x5hbG1VIoH1wGTgY5pH6GWwCQvg3w9fMJks31S9g6fh8PvI2gVZ2Q5m7R45RTwWsjSnDpP1142qUO52GAdAuLD5lQ320T14ORZe7BNXiv5PX5yBFdhu/gFn92t/VIAKpLrXD7r0G0+iu10wOerfOrrs/lqFRc3riUvYy0Dq7dYgPMg0VxnmyUr4u1qFo8Ivzt/FJ+NeSxrZQNQqgXkk3ZJdXQ60TTIlGDhZCLJpMqb4uxSbD70f2xKjgGG2ZUJDm5xflzSOJB2N35rpolknHps4bQ+OksdD6M3+TVqSZlOKmY9rCYgZBHl2y89ZrMQkKdtucH0wBFmHdzRzN5HIj1jGxV4ltkvY4vFQukoTjfZhGg2iWfpFJ/gBuyV9GHSgru4C6yITKRQTybQjfe0UzL5hdGUyWZZyYeJnFaMsfZrSl0sG/or4DFRw="
